### ISSUE TITLE
To do before 1.0.0 release 

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/tidyBF#6]
- [x] cover both *t*-test and ANOVA in a single function (use alias)
- [x] posterior estimates for contingency tabs (https://github.com/easystats/insight/issues/191)
- [x] R-squared for ANOVA designs (https://github.com/easystats/performance/issues/143)
- [ ] rely on `BayesFactor` for one-way table (https://github.com/richarddmorey/BayesFactor/issues/135)
- [x] use `parameters` to tidy `metaBMA` output (https://github.com/easystats/parameters/issues/295)
- [x] make sure functions work within loops and add tests for the same (#11)
- [x] use `model_parameters` to get Cramer's V (https://github.com/easystats/parameters/issues/345)
- [ ] add Cramer's V as effect size for one-way table (when supported in `BayesFactor`)
- [x] have a single expression template used across all functions
- [x] retire `bf_formatter`
- [x] remove `lme4` from `Depends`
- [x] retire `meta_data_check`
- [x] rely on `parameters` to get priors in `model_parameters` output itself (https://github.com/easystats/insight/issues/222)
- [ ] support paired contingency tabs (https://github.com/richarddmorey/BayesFactor/issues/150#issuecomment-731769873)
- [ ] support only `median` + `HDI` posteriors and be more explicit in the expression what kind of posterior it is

**Comment by IndrajeetPatil** [comment]
Replace 

https://github.com/IndrajeetPatil/tidyBF/blob/8990120788ce4bda5865832dc9498e33a851b2e4/R/bf_ttest.R#L80-L91

with

https://github.com/IndrajeetPatil/pairwiseComparisons/blob/7d3cc873319d02c3344a10ab929ef4b08e6d364c/R/helpers.R#L65-L72

**Comment by IndrajeetPatil** [comment]
This of this context and how to resolve it. Will probably have to wait for one-way table support in `BayesFactor`

``` r
library(tidyBF)

# another dataset
df1 <- dplyr::filter(mtcars, am == "0")

set.seed(123)
bf_contingency_tab(df1, am, cyl)
#> Warning in as_tibble(bf.object): restarting interrupted promise evaluation
#> Error in compare(numerator = numerator, data = x): x must be m by n.
```

<sup>Created on 2020-10-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by IndrajeetPatil** [comment]
add a table about estimation + hypothesis testing

**Comment by IndrajeetPatil** [comment]
``` r
# setup
set.seed(123)
library(zeallot)
library(rlang)

# data
df <- data.frame(
  rowid = 1:length(sleep$extra[sleep$group == 1]),
  x1 = sleep$extra[sleep$group == 1], 
  x2 = sleep$extra[sleep$group == 2]
)

# function
foo <- function(data, x, y, paired = FALSE, ...) {
  c(x, y) %<-% c(rlang::ensym(x), rlang::ensym(y))

  data <- as.data.frame(data)
  if (isTRUE(paired)) bf.args <- list(x = data[[2]], y = data[[3]])
  if (isFALSE(paired)) bf.args <- list(formula = rlang::new_formula({{ y }}, {{ x }}))

  rlang::exec(
    .fn = BayesFactor::ttestBF,
    rscale = 0.707,
    paired = paired,
    progress = FALSE,
    data = as.data.frame(data),
    !!!bf.args
  )
}

# betweem
foo(mtcars, am, wt)
#> Bayes factor analysis
#> --------------
#> [1] Alt., r=0.707 : 1383.229 ±0%
#> 
#> Against denominator:
#>   Null, mu1-mu2 = 0 
#> ---
#> Bayes factor type: BFindepSample, JZS

# within
foo(df, x1, x2, paired = TRUE)
#> Bayes factor analysis
#> --------------
#> [1] Alt., r=0.707 : 17.2581 ±0%
#> 
#> Against denominator:
#>   Null, mu = 0 
#> ---
#> Bayes factor type: BFoneSample, JZS
```

<sup>Created on 2020-10-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment]
minor:
have one line instead of these two https://github.com/IndrajeetPatil/tidyBF/blob/8aba7bc7969ee801bb3ae9d1c744936fc1a872be/R/helpers_bf_tests.R#L108-L109

**Comment by IndrajeetPatil** [comment]
remove all `as_tibble(.)` statements when the data is being read; this is unnecessary

**Comment by IndrajeetPatil** [comment]
No need to have all elements on separate lines:
https://github.com/IndrajeetPatil/tidyBF/blob/23ed633f56bcd604091aedda4c4440e518bc2d30/R/bf_expr_template.R#L47-L49

Instead:

``` r
library(ggplot2)

ggplot(mtcars, aes(wt, mpg)) + geom_point() +
  labs(subtitle = substitute("log"["e"]*"(BF"["01"]*")"))
```

![](https://i.imgur.com/9feLvQO.png)

<sup>Created on 2021-01-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment]
The entire `tidyBF` code has now moved to `statsExpressions`: https://github.com/IndrajeetPatil/statsExpressions/pull/59

Start preparing for retirement of this package.
